CREATE TABLE `KTR_USER_INFO` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `ACCOUNT` varchar(20) DEFAULT NULL COMMENT '用户名',
  `NICK_NAME` varchar(50) DEFAULT NULL COMMENT '微信昵称',
  `OPEN_ID` varchar(50) DEFAULT NULL COMMENT '微信UUID',
  `AVATAR_URL` varchar(200) DEFAULT NULL COMMENT '微信头像地址',
  `MODIFY_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='用户信息表';